### ISSUE TITLE
handle different hosts 

### ISSUE THREAD

**Issue by mohabkandil** [ViniciusTei/reactjs-freshchat#21]
my host is { host: "https://wchat.eu.freshchat.com" } this case is not handled in the wrapper

**Comment by mohabkandil** [comment]
var init = function init() {
    window.fcWidget.init({
      host: 'https://wchat.freshchat.com',
      token: token,
      externalId: externalId || '',
      firstName: firstName || '',
      lastName: lastName || '',
      config: {
        headerProperty: {
          hideChatButton: label ? true : false
        }
      }
    });
  };

> line 30 in index.js
we can just have " host: 'https://wchat.freshchat.com' ", be a prop with default value = 'https://wchat.freshchat.com'

**Comment by ViniciusTei** [comment]
Hello, i`ve seen your problmen and will work on it asap. Thanks for your time
